### ISSUE TITLE
doasedit doesn't check return code from editor invocation

### ISSUE THREAD

**Issue by djmattyg007** [AN3223/scripts#1]
If the editor exists with a non-zero exit code, the updated file shouldn't be copied into place, even if there were changes. For example, if I exit `vim` with `:cq`, it will exit with an error code.

**Comment by AN3223** [comment]
I just tried editing a test file with vim, saving with :w and then
exiting with :cq and doasedit immediately exits without ever invoking
doas/dd. This seems like the correct behavior to me. Is this what you're
talking about?

**Comment by djmattyg007** [comment]
It is. I have tested again since filing this issue and it does appear to work correctly. My apologies, I clearly didn't test thoroughly enough initially.

**Comment by AN3223** [comment]
No problem, it happens! :)
