### ISSUE TITLE
vimdiff variant of doasedit

### ISSUE THREAD

**Issue by djmattyg007** [AN3223/scripts#2]
Do you think it would be possible/feasible to implement a version of `doasedit` that worked with `vimdiff`? This use case pops up quite frequently for me when merging upstream changes after package upgrades.

**Comment by AN3223** [comment]
I can see the utility of this feature, but I think it's too complex to
include in doasedit. The temporary files would need to be made ahead of
time and passed to the editor all at once in the same order they came
in. Not impossible, but made difficult by the lack of arrays in POSIX
sh (the only solution I can think of is setting the locale and then
relying on the glob order of the temporary files).

As a security sensitive script it's especially important to be small and
simple so the code can be quickly and easily audited.

You could use this workaround if you only need to modify one of the
files you're doing vimdiff on:

EDITOR='vimdiff file1' doasedit file2

**Comment by djmattyg007** [comment]
> but I think it's too complex to include in doasedit

Sorry for not being clear. I was thinking it could be implemented as an entirely new tool, perhaps named something like `doasdiff` or something along those lines.

What if the script was to be implemented in bash instead of POSIX sh?

**Comment by AN3223** [comment]
Hey let me know how this works for you https://gist.github.com/AN3223/2c9334369215d3a05ac7531334f5f227

**Comment by djmattyg007** [comment]
Wow, you're too kind. It works perfectly :)

**Comment by AN3223** [comment]
No problem :)
